baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Direcţia  de  Asistență Socială Bacău'
theme = 'hugo-cards'

[markup.goldmark.renderer]
	unsafe = true

[params]
	facebook = "https://www.facebook.com/DAS.Municipiul.Bacau"
	email = "contact@dasbacau.ro"
	defaultImage = "daslogo.png"


[taxonomies]
	tag = "tags"
	category = "categories"